spring.application.name=taskManagement

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

logging.file.name=logs/task-management.log

#Batching
spring.jpa.properties.hibernate.default_batch_fetch_size=25

#Mail configurations
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

jwt.secret=${JWT_SECRET}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Flyway config
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.default-schema=public

# Actuator
# management.endpoints.web.exposure.include=* this * includes features like shutdown, env (which returns all env values)...
management.endpoints.web.exposure.include=health,info,metrics 
management.endpoint.health.show-details=when-authorized
# management.info.*=true - returns information like app name et....
# without this below line actuator does kick in
management.info.env.enabled=true

# App info shown in /actuator/info
info.app.name=TaskFlow
info.app.description=Task Management System
info.app.version=1.0.0